language: objective-c

branches:
 only:
 - master

xcode_project: prueba.xcodeproj
xcode_scheme: pruebaTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -project prueba.xcodeproj -scheme pruebaTests -sdk iphonesimulator9.0 test | xcpretty -c
